version: "3"

services:
  svelte:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: "${PROJECT_NAME}"
    restart: always
    command:
      "npm run start"


  nginx:
    image: nginx:1.13
    container_name: "${PROJECT_NAME}_NGINX"
    ports:
      - "4100:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - svelte
